"https://{default}/":
    type: redirect
    to: "https://maison.{default}/"

"https://www.{default}/":
    type: redirect
    to: "https://maison.{default}/"

"https://maison.{default}/":
    type: upstream
    upstream: "varnish:http"
    cache:
        enabled: false

"https://professionals.{default}/":
    type: upstream
    upstream: "varnish:http"
    cache:
        enabled: false

"https://admin.{default}/":
    type: upstream
    upstream: "varnish:http"
    cache:
        enabled: false
